return {
	-- require "plugins.utilities.auto_save.main",
	require "plugins.utilities.autopairs.main",
	require "plugins.utilities.comment.main",
	require "plugins.utilities.hlsearch.main",
	require "plugins.utilities.indent_blackline.main",
	require "plugins.utilities.neocomposer.main",
	require "plugins.utilities.notify.main",
	require "plugins.utilities.persistence.main",
	require "plugins.utilities.relative_toggle.main",
	require "plugins.utilities.sos.main",
	require "plugins.utilities.tmux_navigator.main",
	require "plugins.utilities.treesj.main",
	require "plugins.utilities.ufo.main",
	require "plugins.utilities.which_key.main",
}
